name: ARNs

on: [workflow_dispatch]

env: 
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  APP_ID: books-api
  PIPELINE_USER_ARN: arn:aws:iam::516153165611:user/frank-smartbear
  SAM_TEMPLATE: books-api/template.yaml
  TESTING_STACK_NAME: books-api-dev
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::516153165611:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-N4C4I53NYPV7
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::516153165611:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1T6ILOT1T6KZM
  TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-dev-pipeline-artifactsbucket-24tjq4tlw45r
   
jobs:
  setupARNs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.TESTING_REGION }}
        role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
        role-session-name: testing-packaging
        role-duration-seconds: 3600
        role-skip-session-tagging: true
